/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as authAccountUnavailableRouteImport } from './routes/(auth)/account-unavailable'
import { Route as authCheckEmailRouteImport } from './routes/(auth)/check-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as AuthedAppRouteRouteImport } from './routes/_authed/_app/route'
import { Route as AuthedCompleteProfileRouteImport } from './routes/_authed/complete-profile'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestSignInRouteImport } from './routes/_guest/sign-in'
import { Route as GuestSignUpRouteImport } from './routes/_guest/sign-up'
import { Route as authAuthCallbackRouteImport } from './routes/(auth)/auth/callback'
import { Route as AuthedAppAccountRouteImport } from './routes/_authed/_app/account'
import { Route as AuthedAppBalanceRouteImport } from './routes/_authed/_app/balance'
import { Route as AuthedAppChatIndexRouteImport } from './routes/_authed/_app/chat/index'
import { Route as AuthedAppChatConversationIdRouteImport } from './routes/_authed/_app/chat/$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const authAccountUnavailableRoute = authAccountUnavailableRouteImport.update({
  id: '/(auth)/account-unavailable',
  path: '/account-unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const authCheckEmailRoute = authCheckEmailRouteImport.update({
  id: '/(auth)/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRouteRoute = AuthedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCompleteProfileRoute = AuthedCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignInRoute = GuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignUpRoute = GuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => GuestRouteRoute,
} as any)
const authAuthCallbackRoute = authAuthCallbackRouteImport.update({
  id: '/(auth)/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppAccountRoute = AuthedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppBalanceRoute = AuthedAppBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppChatIndexRoute = AuthedAppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppChatConversationIdRoute =
  AuthedAppChatConversationIdRouteImport.update({
    id: '/chat/$conversationId',
    path: '/chat/$conversationId',
    getParentRoute: () => AuthedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-unavailable': typeof authAccountUnavailableRoute
  '/check-email': typeof authCheckEmailRoute
  '/reset-password': typeof authResetPasswordRoute
  '/complete-profile': typeof AuthedCompleteProfileRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/auth/callback': typeof authAuthCallbackRoute
  '/account': typeof AuthedAppAccountRoute
  '/balance': typeof AuthedAppBalanceRoute
  '/chat/$conversationId': typeof AuthedAppChatConversationIdRoute
  '/chat/': typeof AuthedAppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-unavailable': typeof authAccountUnavailableRoute
  '/check-email': typeof authCheckEmailRoute
  '/reset-password': typeof authResetPasswordRoute
  '/complete-profile': typeof AuthedCompleteProfileRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/sign-in': typeof GuestSignInRoute
  '/sign-up': typeof GuestSignUpRoute
  '/auth/callback': typeof authAuthCallbackRoute
  '/account': typeof AuthedAppAccountRoute
  '/balance': typeof AuthedAppBalanceRoute
  '/chat/$conversationId': typeof AuthedAppChatConversationIdRoute
  '/chat': typeof AuthedAppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteRouteWithChildren
  '/(auth)/account-unavailable': typeof authAccountUnavailableRoute
  '/(auth)/check-email': typeof authCheckEmailRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_authed/complete-profile': typeof AuthedCompleteProfileRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/sign-in': typeof GuestSignInRoute
  '/_guest/sign-up': typeof GuestSignUpRoute
  '/(auth)/auth/callback': typeof authAuthCallbackRoute
  '/_authed/_app/account': typeof AuthedAppAccountRoute
  '/_authed/_app/balance': typeof AuthedAppBalanceRoute
  '/_authed/_app/chat/$conversationId': typeof AuthedAppChatConversationIdRoute
  '/_authed/_app/chat/': typeof AuthedAppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-unavailable'
    | '/check-email'
    | '/reset-password'
    | '/complete-profile'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/auth/callback'
    | '/account'
    | '/balance'
    | '/chat/$conversationId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-unavailable'
    | '/check-email'
    | '/reset-password'
    | '/complete-profile'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/auth/callback'
    | '/account'
    | '/balance'
    | '/chat/$conversationId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_guest'
    | '/_authed/_app'
    | '/(auth)/account-unavailable'
    | '/(auth)/check-email'
    | '/(auth)/reset-password'
    | '/_authed/complete-profile'
    | '/_guest/forgot-password'
    | '/_guest/sign-in'
    | '/_guest/sign-up'
    | '/(auth)/auth/callback'
    | '/_authed/_app/account'
    | '/_authed/_app/balance'
    | '/_authed/_app/chat/$conversationId'
    | '/_authed/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  authAccountUnavailableRoute: typeof authAccountUnavailableRoute
  authCheckEmailRoute: typeof authCheckEmailRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authAuthCallbackRoute: typeof authAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/account-unavailable': {
      id: '/(auth)/account-unavailable'
      path: '/account-unavailable'
      fullPath: '/account-unavailable'
      preLoaderRoute: typeof authAccountUnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/check-email': {
      id: '/(auth)/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof authCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/complete-profile': {
      id: '/_authed/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthedCompleteProfileRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/sign-in': {
      id: '/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof GuestSignInRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/sign-up': {
      id: '/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof GuestSignUpRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/(auth)/auth/callback': {
      id: '/(auth)/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof authAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app/account': {
      id: '/_authed/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAppAccountRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/_app/balance': {
      id: '/_authed/_app/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthedAppBalanceRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/_app/chat/': {
      id: '/_authed/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthedAppChatIndexRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/_app/chat/$conversationId': {
      id: '/_authed/_app/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthedAppChatConversationIdRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
  }
}

interface AuthedAppRouteRouteChildren {
  AuthedAppAccountRoute: typeof AuthedAppAccountRoute
  AuthedAppBalanceRoute: typeof AuthedAppBalanceRoute
  AuthedAppChatConversationIdRoute: typeof AuthedAppChatConversationIdRoute
  AuthedAppChatIndexRoute: typeof AuthedAppChatIndexRoute
}

const AuthedAppRouteRouteChildren: AuthedAppRouteRouteChildren = {
  AuthedAppAccountRoute: AuthedAppAccountRoute,
  AuthedAppBalanceRoute: AuthedAppBalanceRoute,
  AuthedAppChatConversationIdRoute: AuthedAppChatConversationIdRoute,
  AuthedAppChatIndexRoute: AuthedAppChatIndexRoute,
}

const AuthedAppRouteRouteWithChildren = AuthedAppRouteRoute._addFileChildren(
  AuthedAppRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedAppRouteRoute: typeof AuthedAppRouteRouteWithChildren
  AuthedCompleteProfileRoute: typeof AuthedCompleteProfileRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAppRouteRoute: AuthedAppRouteRouteWithChildren,
  AuthedCompleteProfileRoute: AuthedCompleteProfileRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestSignInRoute: typeof GuestSignInRoute
  GuestSignUpRoute: typeof GuestSignUpRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestSignInRoute: GuestSignInRoute,
  GuestSignUpRoute: GuestSignUpRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  authAccountUnavailableRoute: authAccountUnavailableRoute,
  authCheckEmailRoute: authCheckEmailRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authAuthCallbackRoute: authAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
